version: "3"
services:
  srcds:
    image: p0kr/source-dedicated-server
    user: "1000:1000"
    ports:
      - 27015:27015
      - 27020:27020/udp
      - 27005:27005/udp
      - 26900:26900/udp
    volumes:
      - ./root-dir:/home/steam/root-dir
    environment:
      - GAME=${GAME}
      - MAP=${MAP}
      - MAX_PLAYERS=${MAX_PLAYERS}
      - SERVER_TOKEN=${SERVER_TOKEN}
      - WORKSHOP_COLLECTION=${WORKSHOP_COLLECTION}
      - GAME_PORT=${GAME_PORT}
      - SOURCETV_PORT=${SOURCETV_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - STEAM_PORT=${STEAM_PORT}

